version: "3.6"

services:

# -------------------------------------
# GITLAB
# -------------------------------------
  gitlab:
    image: gitlab/gitlab-ce:latest
    ports:
      - "2224:22"
      - "8929:8929"
      - "5001:5001"
    volumes:
      - ./data/gitlab/data:/var/opt/gitlab
      - ./data/gitlab/logs:/var/log/gitlab
      - ./data/gitlab/config:/etc/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab:8929'
        registry_external_url 'http://gitlab:5001'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        gitlab_rails['initial_root_password'] =  'password'
        gitlab_rails['initial_shared_runners_registration_token'] =  'token'
    networks:
      - 'gitlab-network'

# -------------------------------------
# MINIO
# -------------------------------------
  minio:
    image: minio/minio:latest
    volumes:
    - ./data/minio/data:/data
    ports:
    - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    entrypoint: sh
    command: -c 'mkdir -p /data/gitlab && /usr/bin/minio server --compat /data'
    networks:
      - 'gitlab-network'

# -------------------------------------
# GITLAB-RUNNER
# -------------------------------------
  gitlab-runner:
    depends_on:
      - 'gitlab'
      - 'minio'
    image: gitlab/gitlab-runner:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/gitlab-runner/config:/etc/gitlab-runner
    networks:
      - 'gitlab-network'

networks:
  gitlab-network:
    name: gitlab-network