version: "3.6"

services:

# -------------------------------------
# GITLAB
# -------------------------------------
  gitlab:
    image: gitlab/gitlab-ce:latest
    ports:
      - "2224:22"
      - "8929:8929"
      - "5001:5001"
    volumes:
      - ./gitlab/data:/var/opt/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/config:/etc/gitlab
    hostname: 'gitlab.localhost.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.localhost.com:8929'
        registry_external_url 'http://gitlab.localhost.com:5001'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        gitlab_rails['initial_root_password'] =  'password'
        gitlab_rails['initial_shared_runners_registration_token'] =  'token'
    networks:
      default:
        aliases:
          - 'gitlab.localhost.com'

# -------------------------------------
# MINIO
# -------------------------------------
  minio:
    image: minio/minio:latest
    volumes:
    - ./minio/data:/data
    ports:
    - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    networks:
      - 'default'
    command: server /data

# -------------------------------------
# GITLAB-RUNNER
# -------------------------------------
  gitlab-runner:
    depends_on:
      - 'gitlab'
      - 'minio'
    image: gitlab/gitlab-runner:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./gitlab-runner/config:/etc/gitlab-runner
    networks:
      - 'default'

networks:
  default:
    driver: 'bridge'